### ISSUE TITLE
Tracking WebIDL api progress

### ISSUE THREAD

**Issue by k88hudson** [k88hudson/newnewtab#4]
## Prefs
- [x] getCurrent
- [ ] update
- [ ] event listener for updates is working properly
## Sites
- [ ] getFrecent
- [ ] getScreenShot
- [ ] event listener for updates is working properly
## Search
- [x] getSuggestions
- [x] performSearch
- [x] getCurrentEngine
- [x] getVisibleEngines
- [x] goToSearchPrefs
- [x] event listener for updates is working properly
  - [x] when the currentEngine changes
  - [x] when an engine is added or removed
